import type { Metadata } from 'next'
import { Inter, IBM_Plex_Sans } from 'next/font/google'
import './globals.css'
import Sidebar from './components/Sidebar'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

const ibmFlexSans = IBM_Plex_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-ibm-plex-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${ibmFlexSans.variable} antialiased`}
    >
      <body className="font-inter">
        <Sidebar />
        <main className="ml-[9.6875rem] w-[calc(100vw-9.6875rem)] pl-[7.5rem] pr-[3.125rem] pt-10">
          <header className="flex items-center justify-end gap-6 pr-9">
            <button className="font-base rounded-lg px-4 py-[0.625rem] text-black transition hover:bg-purple hover:bg-opacity-15 hover:font-semibold">
              Português - Br
            </button>
            <button className="font-base rounded-lg bg-purple bg-opacity-15 px-4 py-[0.625rem] font-semibold text-black transition hover:bg-purple hover:bg-opacity-15 hover:font-semibold">
              English - US
            </button>
          </header>
          {children}
        </main>
      </body>
    </html>
  )
}
