import type { Metadata } from 'next'
import { Inter, IBM_Plex_Sans } from 'next/font/google'
import './globals.css'
import { Header } from './components/Header'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

const ibmFlexSans = IBM_Plex_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-ibm-plex-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${ibmFlexSans.variable} antialiased`}
    >
      <body className="font-inter">
        <Header />
        <main className="ml-[9.6875rem]">{children}</main>
      </body>
    </html>
  )
}
