local_backend: true

backend:
  name: git-getway
  branch: main
  publish_mode: editorial_workflow

media_folder: public/images
public_folder: /images

collections:
  - name: "config"
    label: "Config"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Config"
        file: "config.json"
        description: "General site settings"
        fields:
          - label: "URL"
            name: "base_url"
            widget: "string"
            hint: "Do not enter the trailing slash of the URL"
          - label: "Site title"
            name: "site_title"
            widget: "string"
          - label: "Site description"
            name: "site_description"
            widget: "string"
          - label: "Site keywords"
            name: "site_keywords"
            widget: "list"
            summary: "{{fields.keyword.keyword}}"
            field:
              label: Keyword
              name: keyword
              widget: "string"
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home"
        file: "store/home.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Content, name: content, widget: markdown}
          - {label: ButtonText, name: buttonText, widget: string}
          - {label: Phone, name: phone, widget: string}
          - {label: Email, name: email, widget: string}
          - {label: Image, name: image, widget: image}
